#!/usr/bin/env ruby
require 'bundler/setup'
require 'active_support/all'
require 'pry'
require_relative 'lib/stream_server'
require_relative 'lib/stream_listener'

servers = StreamServer.all_from_url 'http://provisioning.streamtheworld.com/pls/WPOWFMAAC.pls'
client = StreamListener.new(servers.values.first)
